name: Deploying Catto Botto

on:
  workflow_dispatch:
    inputs:
        environment:
            description: 'Environment to run tests against'
            type: environment
            required: true   
            
jobs:
  deploy:
    runs-on: [self-hosted, Linux, x64, catto]
    environment: ${{ github.event.inputs.environment }}

    env:
      DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
      CLASH_TOKEN: ${{ secrets.CLASH_TOKEN }}
      MONGO_URI: ${{ secrets.MONGO_URI }}    

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup configuration
        run: |
          cp config.json.copy config.json
          cp emojis.json.copy emojis.json
          echo "DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}" > .env
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env
          echo "CLASH_TOKEN=Bearer ${{ secrets.CLASH_TOKEN }}" >> .env
          
      - name: Echo secret
        run: echo "DISCORD_TOKEN is ${{ secrets.DISCORD_TOKEN }}"

      - name: Run npm install
        run: npm install
      - name: deploy-commands.js
        run: node deploy-commands.js
      - name: Start bot with PM2
        run: |
          npx pm2 delete catto-botto || true  
          npx pm2 start index.js --name catto-botto
          npx pm2 save  